### ISSUE TITLE
Recherche linéaire

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#11]
Implémenter un algorithme de recherche linéaire pour trouver un élément dans un tableau.

**Comment by Thescattypotty** [comment]
https://www.delftstack.com/fr/tutorial/algorithm/linear-search/#google_vignette
ne pas voir le code ; merci d'analyser le code et l'algorithm et fais par toi meme

**Comment by Thescattypotty** [comment]
Fiere de toi  , c pas 10/10 mais c'est bien, 
ila mal9inach le nombre maki 2affichi walo , un booleen serait un plus
