### ISSUE TITLE
Vérification des nombres premiers

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#23]
Vérifier si un nombre donné est premier.

**Comment by Thescattypotty** [comment]
c'est faux , 
merci de bien vouloir chercher les notions que tu ne connais pas : 
Nombres premiers
Un nombre entier naturel (supérieur ou égal à 2) est un nombre premier s'il admet exactement 2 diviseurs : 1 et lui-même. Exemple : 2, 3, 5, 7, 11, 13, 17, 19 … sont des nombres premiers. Il en existe une infinité.
