### ISSUE TITLE
Palindromes

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#26]
Vérifier si une chaîne de caractères est un palindrome.

**Comment by Thescattypotty** [comment]
c'est faux !! , mais tu est sur la bonne voie !

definition d'un palindrome : 
Un palindrome est une chaîne qui se lit de la même manière de gauche à droite et de droite à gauche.

exemple que j'ai fait :
java Palindrome
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Donne le mot: yyyyyaaaaahhhy
 palindrome

**Comment by Thescattypotty** [comment]
c'est faux !!
petite astuce :
par exemple le mot athta est palindrome ; car athta = athta (qui est l'inverse du mot initial)
donc prends le mot , et creer une nouvelle chaine de caractere qui est l'inverse du mot , et fais une comparaison .
