### ISSUE TITLE
Gestion de contacts simple

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#30]
Objectif : Créer un programme pour ajouter, afficher et supprimer des contacts (nom et numéro de téléphone).
Concepts : Tableaux ou ArrayList, méthodes.

**Comment by Thescattypotty** [comment]
3wdi 9ray mch hdch li tlebt gestion de contact mch gestion d'etudiant u glt lik nom et numero de téléphone mch age

**Comment by Thescattypotty** [comment]
Un numero de téléphone , ne peut etre de type double !
