### ISSUE TITLE
Calcul de l'IMC (Indice de Masse Corporelle)

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#32]
Calculer l'IMC à partir du poids et de la taille de l'utilisateur et afficher la catégorie correspondante (maigreur, normal, surpoids, obésité).

**Comment by wiameouk** [comment]
verifie moi ce code !

**Comment by Thescattypotty** [comment]
le cas dial 18.5 maghadach traitih ?
khasshk hna :
else if(masseCorporelle > 18.5 && masseCorporelle<25)
diri : 
else if(masseCorporelle >= 18.5 && masseCorporelle<25)
