### ISSUE TITLE
Jeu de devinette

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#34]
Créer un jeu où l'utilisateur doit deviner un nombre aléatoire entre 1 et 100.
Boucles while, conditions if-else, génération de nombres aléatoires (Random).

**Comment by Thescattypotty** [comment]
au lieu de faire while , un do while serait plus judicieux ,car si l'utilisateur entre 1 et random donne 1 , on affichera rien don un do while est plus judicieux !

**Comment by Thescattypotty** [comment]
![Image](https://github.com/user-attachments/assets/216c66da-affc-477b-97a0-3c797fe44d39)

Ce n'est plus un jeu de devinette si tu affiche le nombre aleatoir , soit plus applicatif dans ton travail stp
