### ISSUE TITLE
Nombre de Fibonacci

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#37]
Générer les premiers _n_ nombres de Fibonacci.

**Comment by wiameouk** [comment]
m3rft mn ndir fiha w w5a  fhmt concept  A+b=c => b+c=? etc.......
le code 5awi !

**Comment by Thescattypotty** [comment]
merci de voir la correction : 
https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/
