### ISSUE TITLE
Système de gestion de bibliothèque

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#39]
**Objectif** : Créer une application de gestion de bibliothèque qui permet de gérer les livres, les utilisateurs et les prêts de livres.

**Concepts** : Classes et objets, collections (ArrayList, HashMap), gestion des entrées/sorties de fichiers, exceptions.

**Fonctionnalités** :

Ajouter, modifier, supprimer des livres.
Ajouter, modifier, supprimer des utilisateurs.
Enregistrer et consulter les prêts de livres.
Sauvegarder et charger les données à partir de fichiers.

**Comment by Thescattypotty** [comment]
![Image](https://github.com/user-attachments/assets/3d68d72f-ac1a-410a-a008-1d91db1b8868)



![Image](https://github.com/user-attachments/assets/80248e3a-086d-4a1d-9cd8-7851ec6307d5)

Merci de bien vouloir , revoir ce code , on ne peut afficher un object sans @Overrid toString , cherche toString en java avant de refaire !

et pour le main , creer moi une interface sur commande afin que je fasse ce que je veux !

**Comment by wiameouk** [comment]
je n'ai pas bien compris pour le main , de creer interface sur commande !!
