### ISSUE TITLE
Journalisation avec Timestamp

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#49]
**Objectif** : Combiner la lecture/écriture de fichiers avec la manipulation de dates et d'heures.
**Exercice** : Créer un programme qui enregistre des messages de journal dans un fichier texte. Chaque message doit être précédé d'un timestamp indiquant la date et l'heure actuelles.
**Indice** : utilise java.io et java.time

**Comment by Thescattypotty** [comment]
lcode doit etre bien structuré
