### ISSUE TITLE
Gestion de Tâches avec Dates et Collections

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#51]
**Objectif** : Gérer des tâches avec des dates et des collections.

**Exercice** : Créer un programme qui permet à l'utilisateur de créer, afficher, et supprimer des tâches. Chaque tâche doit avoir une description et une date limite. Utiliser ArrayList pour stocker les tâches et LocalDate pour les dates limites.

**Indice** : utilise java.util et java.time

**Comment by Thescattypotty** [comment]
code non structuré
