### ISSUE TITLE
Calcul de Temps de Traitement

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#57]
**Objectif** : Mesurer le temps de traitement d'un bloc de code.

**Exercice** : Écrire un programme qui mesure et affiche le temps de traitement nécessaire pour trier une grande liste de nombres aléatoires. Utiliser System.currentTimeMillis() ou Instant.now() pour mesurer le temps avant et après le tri.

**Indice** : utilise java.lang & java.time

**Comment by Thescattypotty** [comment]
utilise long aulieu de int , System.currentTimeMillis() return long
