### ISSUE TITLE
Project Final de tous ces packages : Gestion d'un Système de Suivi de Tâches

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#59]
**Objectif** : Créer un programme complet de gestion de tâches qui peut lire et écrire des tâches dans un fichier CSV, et manipuler les dates et heures des tâches.

**Description** :
### 1- Le programme doit permettre à l'utilisateur de :

  -   Ajouter une nouvelle tâche avec une description, une date limite, et une priorité.
  -   Afficher toutes les tâches existantes.
  -   Supprimer une tâche spécifique.
  -   Enregistrer les tâches dans un fichier CSV.
  -   Charger les tâches depuis un fichier CSV.

### 2 - Structure de la Classe Tâche :

  -   Attributs : description (String), date limite (LocalDate), priorité (int).
  -   Implémentez des méthodes toString() pour un affichage facile.

### 3 - Fonctionnalités :

  -   Lecture/écriture de fichiers avec java.io.
  -   Manipulation des chaînes de caractères et opérations diverses avec java.lang.
  -   Utilisation des collections (ArrayList) pour gérer les tâches avec java.util.
  -   Gestion des dates et heures avec java.time.
  -   Utilisation de la bibliothèque com.opencsv pour lire et écrire les fichiers CSV.
  
### 4 - Creer Pour moi un menu avec switch afin que je teste tous ces functionnalité:
 le menu doit etre comme ceci : 

      1. Ajouter une tâche
      2. Afficher les tâches
      3. Supprimer une tâche
      4. Enregistrer les tâches
      5. Charger les tâches
      6.Quitter
### 5 - Packages requis : 
java.lang.* , java.util.* , java.io.* , java.time.*
pour com.opencsv.* merci de ce referer avec ceci : https://mvnrepository.com/artifact/com.opencsv/opencsv
### 6 - Project Init : 
Le project doit etre un project initialisé avec maven : 
 merci de ce referer a ce lien pour creer un project avec maven : https://maven.apache.org/guides/getting-started/
la command pour installtion et lancement de project : mvn clean install .

**Comment by Thescattypotty** [comment]
5 - Packages requis :
java.lang.* , java.util.* , java.io.* , java.time.*
pour com.opencsv.* merci de ce referer avec ceci : https://mvnrepository.com/artifact/com.opencsv/opencsv

6 - Project Init :
Le project doit etre un project initialisé avec maven :
merci de ce referer a ce lien pour creer un project avec maven : https://maven.apache.org/guides/getting-started/
la command pour installtion et lancement de project : mvn clean install .

relie ceci
