### ISSUE TITLE
Table de multiplication

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#7]
Imprimer la table de multiplication d'un nombre donné. avec boucle **For**

**Comment by wiameouk** [comment]
Dans le code de TableMultiple , j'ai essayé de coder avec scanf, mais ça ne marche pas. Je laisse mon code en commentaire pour que tu puisses le vérifier.

**Comment by Thescattypotty** [comment]
Je n'ai pas aimer ton code a refaire !

**Comment by Thescattypotty** [comment]
essaye de demander un nombre X , et tu lui affiche ca table de multi (pas la pein de creer le []tab)
ou bien d'afficher la table de multi de tous les nombre de 1 - 9

**Comment by Thescattypotty** [comment]
c bien mais abnti rah la table de multiplication mn 1 tal 10 hhhhhhhhhhhh mch mn 0 tal 6
