### ISSUE TITLE
Calcul de la factorielle

### ISSUE THREAD

**Issue by wiameouk** [wiameouk/WiameLearning#9]
Calculer la factorielle d'un nombre donné. boucle **for**

**Comment by Thescattypotty** [comment]
merci de voir ce site : https://www.calculatorsoup.com/calculators/discretemathematics/factorials.php
pour voir comment en calcule le factoriel ,
a refaire !! (j'ai remarque du code inutile)

**Comment by Thescattypotty** [comment]
Fiere de toi
